const proof = [
  ['Temporal OSS','5 merged PRs','temporal'], ['Azure SDK','merged PR','azure'], ['AgentGrid','73 tests','agent'], ['Meta PE','Production Engineering','meta'], ['Thales','100k+ telemetry','thales'], ['UF MS CS','3.8 GPA','uf']
];
const nodes = [
  ['Temporal','MERGED','temporal'], ['AgentGrid','EVALUATED','agent'], ['Faultline','VALIDATED','fault'], ['KubePulse','HELD','kube'], ['FairEval','REVIEW','fair'], ['DetTrace','ISOLATED','trace']
];
const projects = [
  {id:'agentgrid',k:'AI WORKFLOW OS',t:'AgentGrid',h:'Runtime graph for tool-use, RAG quality, evaluation gates, telemetry, human review, and handoff readiness.',m:['73 passing tests','5/5 eval checks','0.90 retrieval hit rate','820ms p95 latency'],type:'graph'},
  {id:'faultline',k:'DISTRIBUTED EXECUTION',t:'Faultline',h:'PostgreSQL-backed worker runtime with leases, fencing tokens, retries, idempotency, crash recovery, and commit-boundary validation.',m:['0.0% duplicate commits','1,500+ failure scenarios','37 stale writes rejected'],type:'log'},
  {id:'kubepulse',k:'RELEASE INFRASTRUCTURE',t:'KubePulse',h:'Deployment waves, dependency health, latency signals, rollback workflows, and release review in one operational surface.',m:['5 unsafe releases held','+608% p95 regression','0 false-safe approvals'],type:'release'},
  {id:'faireval',k:'EVALUATION OPERATIONS',t:'FairEval',h:'Model behavior measured through groundedness checks, evaluator reliability, dataset drift, release governance, and Zenodo-published artifacts.',m:['Responsible AI API','Zenodo artifact','release review workflow'],type:'board'},
  {id:'dettrace',k:'REPLAY DIAGNOSTICS',t:'DetTrace',h:'Trace replay infrastructure for first-divergence isolation, failure classification, regression testing, and repeatable C++ diagnostics.',m:['10,000+ trace validations','C++17 diagnostics','step 438 divergence'],type:'trace'}
];
function ProofStrip(){return <div className="proofStrip">{proof.map(([a,b,c])=><div className={`proof ${c}`} key={a}><span>{a}</span><strong>{b}</strong></div>)}</div>}
function SystemGraph(){return <section className="systemGraph" id="systems"><div className="graphHead"><span className="eyebrow">ENGINEERING OPERATING SYSTEM</span><h2>One signal moves through every layer.</h2><p>Open source runtime work, AI workflow infrastructure, distributed execution, release validation, evaluation operations, and replay diagnostics — connected as one systems portfolio.</p></div><div className="graphRail"><div className="signal"></div>{nodes.map(([n,s,c],i)=><div className={`graphNode ${c}`} style={{'--i':i}} key={n}><small>{String(i+1).padStart(2,'0')}</small><b>{n}</b><span>{s}</span></div>)}</div></section>}
function OSS(){return <section className="oss" id="oss"><span className="eyebrow">MAINTAINER-REVIEWED PROOF</span><h2>Code merged into systems I do not control.</h2><p>External maintainers reviewed and merged these contributions into public SDKs — proof beyond self-authored projects.</p><div className="ossGrid"><div><span>TEMPORAL GO SDK</span><strong>5 merged PRs</strong><p>#2200 · #2212 · #2248 · #2298 · #2367</p><small>worker docs · poller instrumentation · async completion correctness · runtime clarity</small></div><div><span>AZURE SDK FOR GO</span><strong>merged PR</strong><p>retry policy · error propagation</p><small>errors.Join behavior · regression coverage · SDK reliability notes</small></div></div></section>}
function Artifact({type}){if(type==='graph')return <div className="artifact graphArtifact"><div className="artifactTop"><span>AGENTGRID / RUNTIME GRAPH</span><b>HEALTHY</b></div><div className="flow"><div>Query<em>.93</em></div><i></i><div>Retrieve<em>.90</em></div><i></i><div>Tool<em>ok</em></div><i></i><div>Evaluate<em>5/5</em></div><i></i><div>Handoff<em>ready</em></div></div><div className="runtimeLog"><p><span>00.00</span> query_received() <b>accepted</b></p><p><span>00.16</span> retrieve_documents() <b>score .93 → .90</b></p><p><span>00.32</span> tool_call() <b>success</b></p><p><span>00.48</span> evaluate_answer() <b>5/5 eval checks</b></p><p><span>00.64</span> handoff_runbook() <b>ready</b></p></div><h3>AI WORKFLOW PLATFORM</h3></div>;
if(type==='log')return <div className="artifact logArtifact"><div className="artifactTop"><span>FAULTLINE / TRANSACTION LOG</span><b>COMMIT SAFE</b></div>{['lease_expired worker_a token=41','ownership_transferred worker_b token=42','commit_attempt worker_a stale_owner','validator_response rejected fencing_token_failed','commit_attempt worker_b current_owner','storage_state committed state_preserved'].map(x=><p key={x}>{x}</p>)}<div className="commitRow"><strong className="bad">41 REJECTED</strong><strong>COMMIT BOUNDARY</strong><strong className="good">42 COMMITTED</strong></div></div>;
if(type==='release')return <div className="artifact releaseArtifact"><div className="artifactTop"><span>KUBEPULSE / RELEASE VALIDATION</span><b>REVIEW</b></div><strong className="bigPct">81%</strong>{['US-East','US-West','EU-West'].map((r,i)=><p className="bar" key={r}><span>{r}</span><i style={{width:[76,84,92][i]+'%'}}></i></p>)}<div className="health"><b>API HEALTHY</b><b>WORKER HEALTHY</b><b>CACHE HEALTHY</b><b className="warn">USER LATENCY +608%</b></div><h3>RELEASE HELD FOR REVIEW</h3></div>;
if(type==='board')return <div className="artifact boardArtifact"><div className="artifactTop"><span>FAIREVAL / RELEASE REVIEW</span><b>CANDIDATE V17</b></div>{[['Quality','PASS'],['Safety','PASS'],['Groundedness','REVIEW'],['Serving','REVIEW']].map(([a,b])=><p className={b==='PASS'?'pass':'review'} key={a}><span>{a}</span><b>{b}</b></p>)}<h3>HOLD FOR REVIEW</h3></div>;
return <div className="artifact traceArtifact"><div className="artifactTop"><span>DETTRACE / REPLAY DEBUGGER</span><b>ISOLATED</b></div><p>trace_a <i></i></p><p>trace_b <i className="split"></i></p><h3>DIVERGENCE @ STEP 438</h3><button>ISOLATED</button></div>}
function Project({p,i}){return <section className={`project ${p.id}`}><div className="projectCopy"><span className="eyebrow">{p.k}</span><h2>{p.t}</h2><p>{p.h}</p><div className="metrics">{p.m.map(x=><span key={x}>{x}</span>)}</div><div className="links"><a>Case study →</a><a>GitHub ↗</a>{p.id==='faireval'&&<a>Zenodo ↗</a>}</div></div><Artifact type={p.type}/></section>}
export default function Page(){return <main><nav><b>Kriti Behl</b><div><a href="#systems">Systems</a><a href="#oss">OSS</a><a href="#contact">Contact</a></div></nav><section className="hero"><div className="heroCopy"><span className="eyebrow">BACKEND · PLATFORM · AI INFRASTRUCTURE</span><h1><span>Backend.</span><span>Platform.</span><span>AI Infrastructure.</span></h1><p>I build engineering systems that teams can measure, debug, validate, and operate — across AI workflows, distributed execution, release infrastructure, evaluation, telemetry, and open-source runtimes.</p><div className="cta"><a href="#systems">Explore systems</a><a>GitHub ↗</a><a>Contact</a></div></div><div className="heroGraph"><div className="heroSignal"></div>{nodes.map(([n,s,c],i)=><div className={`heroNode ${c}`} style={{'--i':i}} key={n}><b>{n}</b><span>{s}</span></div>)}</div><ProofStrip/></section><OSS/><SystemGraph/>{projects.map((p,i)=><Project p={p} i={i} key={p.id}/>) }<section className="contact" id="contact"><h2>Build systems teams can measure, operate, and trust.</h2><p>I am looking for backend, AI platform, and technical operations roles where I can build systems that are measurable, reliable, and useful to the teams who own them.</p><div className="cta"><a>Email</a><a>GitHub</a><a>LinkedIn</a></div></section></main>}
